### ISSUE TITLE
Testbed does not work on the latest version of FF3

### ISSUE THREAD

**Issue by kpreid** [google/caja#1027]
Original [issue 1027](https://code.google.com/p/google-caja/issues/detail?id=1027) created by jasvir on 2009-05-10T06:03:36.000Z:

<b>What steps will reproduce the problem?</b>
1. Load http://cajadores.com/demos/testbed
2. On FF 3.08 on Linux and FF 3.0.10 Mac, LiveConnect fails with an error:
&quot;getVersion.getCajoler is not a function&quot; and the copyright notice and
version fail to appear.  It works correctly on FF 2.0.17 on Windows.
